### ISSUE TITLE
Proposal for MR data classification

### ISSUE THREAD

**Issue by gsfr** [scitran/core#402]
The purpose of this classification proposal is to capture how users _think_ about their data and how they would want to _search_ for it, but not to be a ground truth, MR physics-based classification that could be used by processing algorithms.

MR data will be classified according to the following **aspects**, which are all multi-select.

- **Contrast:** B0, B1, T1, T2, T2*, PD, MT, ASL, Perfusion, Diffusion, Spectroscopy, Susceptibility, Velocity, Fingerprinting
- **Intent:** Localizer, Shim, Calibration, Fieldmap, Structural, Functional, Non-Image
- **Features:** Quantitative, Multi-Shell, Multi-Echo, Multi-Flip, Multi-Band, Steady-State, 3D, Compressed-Sensing, Eddy-Current-Corrected, Fieldmap-Corrected, Gradient-Unwarped, Motion-Corrected, Physio-Corrected, Derived, In-Plane

---

Beyond Neuro MR...

- **Specimen:** Phantom, Human, Animal, [or list of animals]
- **Anatomy:** Head, Neck, Upper Extremities, Chest, Abdomen, Spine, Pelvis, Lower Extremities, Other

---

Next steps:
- get input from more users
- define mappings for all BIDS types
- consider renaming `measurements` DB key to `classification`

**Comment by chrisfilo** [comment]
Mapping of the basic BIDS dat types:
- _T1w : Contrast == T1, Intent == Structural
- _T2w : Contrast == T2, Intent == Structural
- _T1map : Contrast == T1, Intent == Structural, Features == Quantitative (however we are considering just storing the INV1 and INV2 from the MP2RAGE sequence and leaving the reconstruction to the user)
- _T2map : Contrast == T2, Intent == Structural, Features == Quantitative
- _bold : Contrast == T2*, Intent == Functional 
- _dwi : Contrast == Diffusion, Intent == Structural

Comments/Questions:
- There are more structural scan types in BIDS, but I only focused on the most common ones.
- Discussion about how to model multi-echo data in BIDS is still ongoing.
- In your nomenclature is multi flip angle considered multi-echo?
- How do you model sequences like MP2RAGE with multiple inversion times?
- How do you model fieldmaps? In BIDS there are 4 different ways data useful for generating fieldmaps can be stored: https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.fcegd01wpsf8
- I would suggest leaving "Corrections" out of this spec and focus on raw data coming out of the scanner. Preprocessing is another can of worms.

**Comment by gsfr** [comment]
Thanks, @chrisfilo. I'm not an expert, but would kindly ask @bobd for his thoughts on your comments.

Please note that the purpose of this classification proposal is to capture how users *think* about their data and how they would want to *search* for it, but not to be a ground truth, MR physics-based classification that could be used by processing algorithms. I'll also update the original post with this language.

**Comment by rfdougherty** [comment]
I think the mapping looks reasonable. As for the comments/questions, I first have a general comment (maybe 'rant' is a better word). I find it confusing to conflate the raw files used to compute a quantitative metric (T1, T2, fieldmap, etc.) with that metric. E.g., calling the multi-inversion scans or mulit-flip scans '_T1map'. I think just storing the raw images as generic structurals is better, reserving 'XXmap' for the quantitative map that is computed from them.  

* I would keep multi-flip distinct from multi-echo. They mean very different things in terms of the pulse sequences and are also generally used differently by end-users. (multi-flip for quantifying T1, multi-echo for qT2 or BOLD artifact removal).
* As noted above, I'd just store multi-inversion, multi-sflip, etc. as structurals, with the relevant parameter available so that they can be easily used to compute the quantitative map. It might be useful to be able to mark a set of images that form a useful 'group'. E.g., the multi-inversion scans are grouped together so a processor can easily grab them to compute a T1map.
* Same for fieldmaps-- I'd reserve 'fieldmap' for the actual fieldmap (I think that's your 3rd option), and just 'goup' the raw images useful for computing a fieldmap.

**Comment by gsfr** [comment]
Thanks, @rfdougherty. I added multi-flip to the features above.

Do we also need a 'fieldmap' feature, akin to quantitative? Not to be confused with fieldmap-corrected.

**Comment by gsfr** [comment]
The answer is no. Fieldmaps would be represented as "B0, quantitative" or "B1, quantitative".

**Comment by mattmiddione** [comment]
Compressed Sensing, Fingerprinting, Localizers, High Order Shim, Calibration Scans, Anatomy, and Perfusion vs. ASL

**Comment by gsfr** [comment]
The existence of *intent* edge cases, such as *functional localizers* has been pointed out. In response, I'm removing the single-select restriction on *intent* and hence simplifying all classification aspects to multi-select.

**Comment by gsfr** [comment]
Merged *features* and *corrections*, per discussion with @lmperry.

**Comment by gsfr** [comment]
@lmperry Per today's conversation, should we add a *Derived* feature here?

**Comment by gsfr** [comment]
Added *Derived* feature above.

@nagem Please incorporate accordingly.

**Comment by gsfr** [comment]
Added *Non-Image* intent.

cc @ryansanford, @nagem, @lmperry

**Comment by ryansanford** [comment]
FYI @dpuccetti DICOM Viewer should not launch for `Non-Image` intent on `dicom` types

**Comment by gsfr** [comment]
@nagem Added _In-Plane_ feature.

**Comment by gsfr** [comment]
@nagem Added _Fieldmap_ intent.

**Comment by ehlertjd** [comment]
I think Phase fits in as a feature -- used in Susceptibility Weighted Imaging.
