### ISSUE TITLE
Listing jobs does not translate "inputs" field from DB representation to Job model representation

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#420]
When a new Job is added, the inputs property is an object.  When JobsHandler saves the job to the database, it translates "inputs" property to an array of objects.  https://github.com/scitran/core/blob/master/api/jobs/jobs.py#L147

@nagem Can you explain why we made this change?  In a comment in database.py you reference scitran/core issue #363 , I wasn't sure what the relation was.

https://github.com/scitran/core/commit/85eb1c110239e2936b68e485e3c777e9cba3275a

**Comment by nagem** [comment]
Oh I probably ref'd the wrong issue #, here is the correct one: https://github.com/scitran/core/issues/362

**Comment by nagem** [comment]
We need to search the jobs table for jobs that reference specific containers (acquisitions, mostly) fairly often. If the `inputs` field is a dict with arbitrary keys, we cannot index on the container id and queries become complex (as you can see by [this old JS query](https://github.com/scitran/core/commit/4e8171500770103bbcdc95f49700a8ac47d1f12d#diff-7c6647ff2f2d4b5702cde704e02c4d9bR139)). 

We did not change how the `inputs` field is represented in the Job class, only how it is stored in Mongo.

**Comment by kofalt** [comment]
To clarify, in memory the `inputs` property is a string -> FileReference map.

Megan is spot on regarding the change, basically mongo does not seem to have good support for wildcard map keys. Finding a match on the far side of an arbitrary key is something that (based on our research) they discourage; making it an array fixes the problem.

The change you link in `load()` and `mongo()` sidestep what would otherwise require changing an object and all its methods each time the database limits how we store our data.

**Comment by coltonlw** [comment]
I see the change in load() to translate back from the DB representation to the Job representation.  What threw me is we forget to change the code for listing all jobs to do this as well:

https://github.com/scitran/core/blob/master/api/jobs/handlers.py#L283

The result is listing jobs shows inputs formatted as a list, whereas creating a job or detailing a job show the dictionary representation.  Thanks for taking the time to explain.

**Comment by kofalt** [comment]
Hah! Yes, that looks like a bug to me.

**Comment by coltonlw** [comment]
@ryansanford Is it possible to add this to current sprint?
