### ISSUE TITLE
Introduce scheduled_run_time for job documents

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#427]
It is not intuitive that `jobs/next` returns jobs ordered by their modification time, and that updating a job would drop it to the bottom of the queue.

Suggest introducing a scheduled_run_time field that defaults to the creation datetime, but can be set when creating jobs by hand.

Beyond decoupling execution order from modification time, this would enable a single ordered query for the jobs now flag, and enable certain jobs to be queued for delayed execution, such as nights and weekends.

Priority is currently not urgent.

**Comment by kofalt** [comment]
Hmm, it would make more sense to have the queue ordered by `created` instead of `modified` in any event. That would be pretty straightforward to change if we didn't want to chase this ticket. The queue was written on the assumption that `modified` = `created` for all pending jobs.

Questions:

1. In what scenario might a job be modified after adding it to the queue, but before it runs?

1. Would you agree with this implementation of `scheduled_run_time`?
  * Queue searches `scheduled_run_time` <= time.now, orders by same field (ascending)
  * If no results, return no work on jobs/next (delaying jobs scheduled in the future)
  * `now` flag is removed; replicate behaviour by setting `scheduled_run_time` to epoch

**Comment by kofalt** [comment]
One quirk with this proposal is that I would like the queue system to be open to non-FIFO ordering in the future, so `scheduled_run_time` might not always be the best name for the field... but not a huge concern.

**Comment by kofalt** [comment]
Also worth noting that if you have queue consumers using the tags parameter (selectively choosing which jobs to run) it might be confusing to see a job that was "scheduled" 5 hours ago, but will actually *never* run in the current environment.

**Comment by ryansanford** [comment]
> Questions:
> 
> 1. In what scenario might a job be modified after adding it to the queue, but before it runs?

If a job got queued for future execution, but an administrator later wants to change it to a different time in the future, or at the end of any current backlog.

> 2. Would you agree with this implementation of `scheduled_run_time`?
>   * Queue searches `scheduled_run_time` <= time.now, orders by same field (ascending)
>   * If no results, return no work on jobs/next (delaying jobs scheduled in the future)
>   * `now` flag is removed; replicate behaviour by setting `scheduled_run_time` to epoch
> 

I foresee `now` flag being removed, or transitioning into a priority designation.

> Also worth noting that if you have queue consumers using the tags parameter (selectively choosing which jobs to run) it might be confusing to see a job that was "scheduled" 5 hours ago, but will actually never run in the current environment.

I agree, however, this concern exists irregardless of a `scheduled_run_time` enhancement.
