### ISSUE TITLE
Move CURRENT_DATABASE_VERSION into api

### ISSUE THREAD

**Issue by coltonlw** [scitran/core#479]
The variable CURRENT_DATABASE_VERSION stored in bin/database.py may be more useful if it was stored in a module of the api.  The API could then compare that variable against what's in the version singleton in the db and if there is a mismatch refuse to start without manual intervention.

**Comment by kofalt** [comment]
Thoughts:

1. It's nice to have the database script be the single place to update the database
1. It's (implicitly right now, oops) required that a hosting infrastructure database.py before launching, and react intelligently based on the exit codes.

Since DB checkpointing is such an "exercise left to the reader" situation, I'd argue that instead of moving this check we could instead do a better job of documenting infrastructure requirements, maybe in the wiki. Perhaps a Hosting Scitran Core page?

**Comment by coltonlw** [comment]
Initial state validation is an application concern and should take place during application startup.  If we wish to rely on database upgrade to validate / ensure startup state, then we should always run the database upgrade as part of our application startup.  If we wish to allow users to start the API without upgrading the database and make the database upgrade an optional infrastructure concern, then initial state validation should be added separately to the application startup code.

**Comment by coltonlw** [comment]
I want to add I don't think automatically upgrading the db on startup is reasonable for us at all especially if multiple instances of the API were ever going to be run in load balanced cluster.  I opened the ticket because I wanted to prevent someone from accidentally starting the app with a mismatched version of the db which could be accomplished easily by adding a version check on startup.  I was not proposing we modify the existing check, rather to move the db version variable for easy access by the startup code.  I agree when adding upgrade code it's most intuitive if the db version variable is in the same file.  As an alternative to moving the variable we could move database.py into the api/ package and have the script in bin/ be a wrapper.
