### ISSUE TITLE
Subject updates are not always reflected on the project report

### ISSUE THREAD

**Issue by dpuccetti** [scitran/core#484]
After updating race/ethnicity the projects report does not always get updated.  It seems to be related to specific subjects, here is one example from dev.flywheel:

https://dev.flywheel.io/#/dashboard/session/576be45259b2b6346719ed71?tab=subject

**Comment by nagem** [comment]
@dpuccetti @elisapoquette, it looks like the Emotion Regulation project has 5 subjects, each with two sessions. The subjects came in with the same subj_code, so we gave them the same `id` in the db to keep them together. Looks like someone modified one of `emoreg_s5`'s codes to be `Test Subject 1`, which makes it appear as a different subject but the backend still connects it to the existing `emoreg_s5` subject info. 

As I mentioned offline, we combine subjects by subject `id` in order to report them only once, and the subject still labeled `emoreg_s5` was the most recently created, so it took precedence in the report, "covering up" the data you expected to see for `Test Subject 1`.

This might open up a bigger question of "what should we do if the user modifies the subject code? Should it get a new id? Probably.

**Comment by nagem** [comment]
If that explanation is sufficient, feel free to close this ticket. We can open a new one for dealing with subject code changes, if necessary.
