### ISSUE TITLE
Support UWSGI running with multiple threads

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#573]
We wish to support multiple threads for maximum flexibility for service scaling.

Related to https://github.com/scitran/core/issues/569

Address the issue of the ref resolver in that issue not being thread safe. May need to open an issue against the relevant project.

@coltonlw This is lower priority than completion of the RAML spec. I am assigned this to the next sprint for the moment.

**Comment by coltonlw** [comment]
@ryansanford RefResolver will most likely not be made thread safe.  Our problem was sharing one instance of a RefResolver between threads.  I will talk to you more offline about threading performance in CPython and thread safety in our codebase to explain why I recommended we disable threads instead of changing our RefResolver caching to be thread safe.

**Comment by coltonlw** [comment]
Contributing thread safety to RefResolver might actually be a great solution I shouldn't have said it's not likely, I honestly don't know if they would appreciate that.  It would be great if the entirety of scitran/core was thread safe and I think moving forward paying attention to thread safety is a good idea.  If you're saying we must have the premature optimization because it's good for the project / future-proofing then we'll refactor for thread safety.  If you're interested in time/complexity investment vs actual performance then we should run performance tests and see how much time we spend on I/O to mongo and nginx, what kind of improvements we see with multiple threads, and if there are any issues with lock contention or otherwise.

**Comment by coltonlw** [comment]
@gsfr Figured you would have an opinion on this ^^^  I would love to contribute thread safety to the project, just trying to make sure this isn't an X Y problem and that you understand the complexity of the task before we take that on

**Comment by gsfr** [comment]
Thanks, @coltonlw. I believe I do understand the complexity. The project has been thread-safe for many years, and I'm hoping we don't have to give that up now, all performance and scaling considerations aside. As @ryansanford points out above, we should give ops maximum flexibility to optimize prod deployments for given usage patterns and hardware, which are yet completely unknown to us.

I take it you have seen https://github.com/Julian/jsonschema/issues/223.

As a quick fix, couldn't we stop caching RefResolvers and simply create a new one when we need it?

**Comment by coltonlw** [comment]
All correct and I hadn't seen that issue before thank you.  I think not caching ref resolvers or making the resolver cache a thread local variable would both be good solutions. Now that I know thread safety has been taken into consideration I think making a contribution to jsonschema like you originally suggested would be great.  If we can re-enable threads after that one change and confidently troubleshoot any hopefully rare issues we do come across, then that sounds good and I just had a misunderstand on my side.
