### ISSUE TITLE
UID upload with matching UID to different project is ignored

### ISSUE THREAD

**Issue by ryansanford** [scitran/core#622]
My understanding is that the same UID is allowed across project boundaries, but not within.

This is being observed with tag https://github.com/scitran/core/tree/1.0.54 and stores from orthanc_reaper version https://github.com/scitran/reaper/tree/1.0.4

@gsfr Are there any workflow concerns at Stanford?

**Comment by gsfr** [comment]
Famous last words: This is a feature, not a bug.

UID uploads are directed to wherever the most specific UID (acquisition or session) already exists in the DB, regardless of project. We only look at the sorting info, if neither UID exists in the system. This is necessary because users have a tendency to move sessions to other projects while data collection is still ongoing. Otherwise, sessions may get split across project, which would be unexpected and extremely annoying, since we don't have merge functionality. Bottomline, we can't really change this.

Repeat uploads are not actually ignored, but rather quietly overwrite existing data.

If it is desired to have the same data in different projects, label upload should be used. Even that violates the basic intent of our strict hierarchy (this is where collections come), but is necessary to accommodate user/web/cli uploads.

**Comment by nagem** [comment]
"fixed" in #770.

There are now two endpoints,`/upload/uid` does what Ryan was expecting, the `/upload/reaper` is where the old logic was moved.
