### ISSUE TITLE
Data Consumption Report

### ISSUE THREAD

**Issue by nagem** [scitran/core#738]
Add endpoints to support a consumption report.

Requirements:
  - [x] Allow user to enter date range for results
  - [ ] Group by: 
    - [ ] Project
    - [ ] Month
  - [ ] For each Project/Month: 
    - [ ] Session count
    - [ ] MBs of files
    - [ ] Gear execution count

**Comment by nagem** [comment]
@ryansanford @lmperry a few questions:

Does gear execution count only include jobs marked as "complete"?

Is it alright that MBs of files by month is only referencing total MBs for *sessions created* in that month? I.e. if you add an analysis today to a session created last month, you would see the MB total go up for last month? Is the session creation time the root time used for calculation?

**Comment by nagem** [comment]
Some objects don't have their own created/modified time (files, for example). What about an acquisition added to a session from last month? Or a gear run across data from several containers?

**Comment by ryansanford** [comment]
@nagem 
Intent is that the MBs of files number would represent any file, not just those in new sessions/acquisitions.

To fulfill that vision, we'd need timestamp and size on files, and indexes on all the places they are sprinkled throughout the mongo collections? Does mongo have restrictions on indexes  of a field within nested lists?

For the purpose of usage report, I'm thinking gears execution be tied to the container holding the output. Thoughts @lmperry ? Analysis attached to a collection would currently not be represented in the report for a project, since collections don't require a project as a parent.

**Comment by nagem** [comment]
Thanks @ryansanford. Files coming from all containers (projects, sessions, acquisitions, analyses) was assumed, I was just giving some examples of discrepancies when adding new data to containers from previous months. 

You can add nested field indexes for one list, not sure about a list within a list. It appears so but Mongo suggests not creating data structures that are doubly nested so behavior and performance might take a hit.

**Comment by nagem** [comment]
Correction - I was incorrect about file timestamps, they do exist everywhere. No change needed there.
