### ISSUE TITLE
If job creation fails during analysis creation, the analysis persists

### ISSUE THREAD

**Issue by nagem** [scitran/core#775]
We currently add the analysis to it's container in the db, create the job doc in the db, and then attach them. This method leaves an unusable analysis when the job creation fails. There are several ways to fix this:
  - clean up the analysis if the job creation fails. This would create a situation where a GET on the analysis's container might return this container during the short interval between anaysis creation and job attempted creation, but is a rare and minimally problematic race condition. (Also, this is possible now).
  - Generate an id for the analysis, add the job (which needs the analysis id for its destination key), and then add the analysis. If the analysis addition fails, we'll be in a similar but opposite situation - except failure is more problematic (engine picks up job before it is remove, etc).
  - Some kind of overengineered batch update to ensure there is minimal chance for race condition.

If anyone has another idea, feel free to suggest. It's a pretty classic circular reference problem.

**Comment by kofalt** [comment]
I'm not super worried by a race condition because we accept those as part of our choice of database. I'm a fan of your first approach - attempt to clean up dependent documents if sibling creation fails.

We could also add a new queue state `hold` which will not be consumed, are fully mutable, can be deleted (!), and can only transition to `pending` or `cancelled`. That would be a clean approach to your second option: the job sits forever until & unless it is complete and ready to be consumed.

Also: heh, I just realized I misspelled that state when I wrote the job queue. Nice :sunglasses: :+1:

**Comment by nagem** [comment]
I like the addition of the `hold` state - I think there are other applications for it than just this one, too.

I think to resolve this current issue I'll do step #1 and reference this ticket (but not close it) and we can revisit if there is a larger jobs enhancement is the works (or when we break analyses into their own mongo connection).

**Comment by kofalt** [comment]
SGTM.
