### ISSUE TITLE
Analysis jobs have different behavior

### ISSUE THREAD

**Issue by kofalt** [scitran/core#953]
Specifically, the `inputs` and `destination` key with information about base-files and the destination container is not set up, because that logic is in the job-add handler. We need a new function on the Job object to handle that logic.

**Comment by ryansanford** [comment]
Consequence is that Analysis jobs don't pass along input file and hiearchy meta to the gear? Is there a workaround?

Thanks.

**Comment by kofalt** [comment]
Correct. Workaround for now is to set the gear to a utility category.

**Comment by ryansanford** [comment]
HCP pipeline gear requires this file meta and context. This will be a blocker for that soon, and impacting the dev workflow because of the large number of files being output into the acquisition.

fmriprep gear, Jen is confirming if her use case is impacted by this. If it is, we will want a quick turnaround this week.

**Comment by jenreiter** [comment]
I uploaded an SDK gear as an "analysis" gear and it failed where it succeeds as a utility gear... https://gears.dev.flywheel.io/#/dashboard/project/59b8296bc4fdd5001e1e8184/session/59c12c3f9019a71e38722d3e?tab=jobs

I am assuming that occurred because the destination is not set.

I need this functionality for my fmriprep gear because it needs to be an analysis gear.

**Comment by nagem** [comment]
Thanks @jenreiter for looking into it. I'll work with @kofalt on getting the endpoints to call the same code paths again.

**Comment by kofalt** [comment]
A fix for this (will be) #938

**Comment by nagem** [comment]
Fixed in #938
